services:
  db:
    image: postgres:16-alpine
    container_name: quickscan_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db


  redis:
    image: redis:7-alpine
    container_name: quickscan_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:

