"""Add enrollment code

Revision ID: 544ef1216da3
Revises: 7ed2be47d9a2
Create Date: 2026-03-26 23:20:20.687716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544ef1216da3'
down_revision: Union[str, Sequence[str], None] = '7ed2be47d9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('enrollment_code', sa.String(length=10), server_default='MIGRATION', nullable=False))
    
    # Backfill with unique values using prefix of UUID
    op.execute("UPDATE sessions SET enrollment_code = upper(substr(id::text, 1, 6))")
    
    op.create_index(op.f('ix_sessions_enrollment_code'), 'sessions', ['enrollment_code'], unique=True)
    op.drop_constraint(op.f('users_department_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'department_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_department_id_fkey'), 'users', 'departments', ['department_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_sessions_enrollment_code'), table_name='sessions')
    op.drop_column('sessions', 'enrollment_code')
    # ### end Alembic commands ###
