"""Add geolocation to sessions, attendance geoloc, audit_ledger

Revision ID: 5e8692fe786e
Revises: ba18a323aabc
Create Date: 2026-03-23 19:01:19.465393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e8692fe786e'
down_revision: Union[str, Sequence[str], None] = 'ba18a323aabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_ledger_action'), 'audit_ledger', ['action'], unique=False)
    op.add_column('attendance', sa.Column('scan_latitude', sa.Float(), nullable=True))
    op.add_column('attendance', sa.Column('scan_longitude', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('sessions', sa.Column('radius_meters', sa.Integer(), server_default='50', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'radius_meters')
    op.drop_column('sessions', 'longitude')
    op.drop_column('sessions', 'latitude')
    op.drop_column('attendance', 'scan_longitude')
    op.drop_column('attendance', 'scan_latitude')
    op.drop_index(op.f('ix_audit_ledger_action'), table_name='audit_ledger')
    op.drop_table('audit_ledger')
    # ### end Alembic commands ###
