"""drop_device_id_unique_constraint

Revision ID: 7ed2be47d9a2
Revises: d8fde306bf38
Create Date: 2026-03-24 10:14:42.821334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ed2be47d9a2'
down_revision: Union[str, Sequence[str], None] = 'd8fde306bf38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_device_id_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_device_id_key'), 'users', ['device_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
