"""Add roll_no to users

Revision ID: 92c3fac6449a
Revises: 544ef1216da3
Create Date: 2026-03-26 23:30:52.547817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92c3fac6449a'
down_revision: Union[str, Sequence[str], None] = '544ef1216da3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('roll_no', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_roll_no'), 'users', ['roll_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_roll_no'), table_name='users')
    op.drop_column('users', 'roll_no')
    # ### end Alembic commands ###
