"""Fix enrollment FK and add audit_ledger adjustments

Revision ID: d8fde306bf38
Revises: 5e8692fe786e
Create Date: 2026-03-23 19:08:47.775778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fde306bf38'
down_revision: Union[str, Sequence[str], None] = '5e8692fe786e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('enrollments_session_id_fkey'), 'enrollments', type_='foreignkey')
    op.create_foreign_key(None, 'enrollments', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'enrollments', type_='foreignkey')
    op.create_foreign_key(op.f('enrollments_session_id_fkey'), 'enrollments', 'users', ['session_id'], ['id'])
    # ### end Alembic commands ###
